### PR TITLE
caffeine: Fix audio desync on stream start

### PR DESCRIPTION
**Pull request by cogwheel**
This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/18)

### CODE REVIEW

**Review by trilorez — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/18)* status: all files reviewed, 3 unresolved discussions (waiting on @cogwheel)

___
*[plugins/caffeine/caffeine-output.c, line 1044 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/18#-LY5-bKC2CGOH2HzdY5h:-LY5-bKC2CGOH2HzdY5i:b7mdsbd) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a56c3fc8a2649c9097594efb7e5e4fd77fad23db/plugins/caffeine/caffeine-output.c#L1044)):*
> ```C
> }
> 
> static bool prepare_audio(struct caffeine_output *context,
> ```

What exactly is this function doing?
___
*[plugins/caffeine/caffeine-output.c, line 1050 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/18#-LY4zoi67U1ROyqTxbDK:-LY4zoi67U1ROyqTxbDL:bce4qy9) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a56c3fc8a2649c9097594efb7e5e4fd77fad23db/plugins/caffeine/caffeine-output.c#L1050)):*
> ```C
> 
> 	if (frame->timestamp < context->start_timestamp) {
> 		uint64_t duration = (uint64_t)frame->frames * 1000000000 / (uint64_t)48000;
> ```

Where is this big number coming from? Also it would be better to have a constant for the sample rate.
___
*[plugins/caffeine/caffeine-output.c, line 1080 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/18#-LY5-7q-3Qh6AjDyypJA:-LY5-7q-3Qh6AjDyypJB:b-43omxw) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a56c3fc8a2649c9097594efb7e5e4fd77fad23db/plugins/caffeine/caffeine-output.c#L1080)):*
> ```C
> 	if (!context->start_timestamp)
> 		return;
> 	if (!prepare_audio(context, frames, &in))
> ```

Is this supposed to have a `return` after it?

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/18)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @trilorez)

___
*[plugins/caffeine/caffeine-output.c, line 1044 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/18#-LY5-bKC2CGOH2HzdY5h:-LY8RRKqEr1au3rF1ed7:bujo9wy) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a56c3fc8a2649c9097594efb7e5e4fd77fad23db/plugins/caffeine/caffeine-output.c#L1044)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

What exactly is this function doing?
</blockquote></details>

Will add a comment about it - works around a known audio desync issue in OBS for unencoded outputs
___
*[plugins/caffeine/caffeine-output.c, line 1050 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/18#-LY4zoi67U1ROyqTxbDK:-LY8Rd7GEOJoRaMcZIQ3:bqog80t) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a56c3fc8a2649c9097594efb7e5e4fd77fad23db/plugins/caffeine/caffeine-output.c#L1050)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Where is this big number coming from? Also it would be better to have a constant for the sample rate.
</blockquote></details>

Agreed
___
*[plugins/caffeine/caffeine-output.c, line 1080 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/18#-LY5-7q-3Qh6AjDyypJA:-LY8RfHv2rlEaeqP2liE:bb6un1j) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a56c3fc8a2649c9097594efb7e5e4fd77fad23db/plugins/caffeine/caffeine-output.c#L1080)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Is this supposed to have a `return` after it?
</blockquote></details>

Done

**Review by trilorez — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/18)* status: all files reviewed, 2 unresolved discussions (waiting on @trilorez)

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/18)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @trilorez)

___
*[plugins/caffeine/caffeine-output.c, line 1044 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/18#-LY5-bKC2CGOH2HzdY5h:-LZarhJtAQ94TwaKlhh8:b-896fix) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a56c3fc8a2649c9097594efb7e5e4fd77fad23db/plugins/caffeine/caffeine-output.c#L1044)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Will add a comment about it - works around a known audio desync issue in OBS for unencoded outputs
</blockquote></details>

Done.
___
*[plugins/caffeine/caffeine-output.c, line 1050 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/18#-LY4zoi67U1ROyqTxbDK:-LZarhwq6NP3YJjfD-6Q:b-896fix) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a56c3fc8a2649c9097594efb7e5e4fd77fad23db/plugins/caffeine/caffeine-output.c#L1050)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Agreed
</blockquote></details>

Done.

**Review by trilorez — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/18)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
