### PR TITLE
Use New Reyes API

### PR DESCRIPTION
**Pull request by trilorez**
Note: if stream heartbeating fails, the broadcast goes offline. In the future it would be better to try to setup a new stream instead.

This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13)

### CODE REVIEW

**Review by cogwheel — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13)* status: all files reviewed, 7 unresolved discussions (waiting on @trilorez and @davidc604)

___
*[plugins/caffeine/caffeine-api.c, line 1013 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8iQVj9mQfwtj6iIeJ:-LU8iLRB54WHDkG6Gz6C:bhmg9i) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-api.c#L1013)):*
> ```C
> 
> 	response = bzalloc(sizeof(struct caffeine_heartbeat_response));
> 	response->connection_quality = bstrdup(connection_quality);
> ```

Do we want to do anything with this value besides forwarding it in other requests? e.g. `<insert whatever Lucio does here>`
___
*[plugins/caffeine/caffeine-output.c, line 350 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8n3Zs31v4cQdvlgL8:-LU8n3Zs31v4cQdvlgL9:bbprf4p) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L350)):*
> ```C
> 
> 	return success;
> }
> ```

Would it make sense for the new functions above here (request_stage_update, set_string, generate_unique_id, transfer_stage_data) to live in caffeine-api instead?
___
*[plugins/caffeine/caffeine-output.c, line 372 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8nWBWDzSVNekldtP2:-LU8nWBWDzSVNekldtP3:b-y4peaz) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L372)):*
> ```C
> 	char * username = bstrdup(
> 		obs_service_query(service, CAFFEINE_QUERY_USERNAME));
> 	char * raw_title = obs_service_query(service, CAFFEINE_QUERY_BROADCAST_TITLE);
> ```

Should be `const` since this isn't being duped?
___
*[plugins/caffeine/caffeine-output.c, line 526 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8fs1B2WIrr0RBhGB5:-LU8fs1B2WIrr0RBhGB6:blzwbhp) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L526)):*
> ```C
> 		}
> 	}
> ```

Looks like there's some mixed spaces & tabs in here
___
*[plugins/caffeine/caffeine-output.c, line 532 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8oZAn3j8QGKwJFcw2:-LU8oZAn3j8QGKwJFcw3:b-ipoi1p) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L532)):*
> ```C
> // Falls back to obs_id if no foreground game detected
> static char const * get_running_game_id(
>     struct caffeine_games * games, const char * obs_id)
> ```

Nit: maybe `fallback_id` would be a better name here?
___
*[plugins/caffeine/caffeine-output.c, line 727 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8b68aDISEWTn0kr_a:-LU8b68aDISEWTn0kr_b:b-b11dav) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L727)):*
> Note: if stream heartbeating fails, the broadcast goes offline. In the future it would be better to try to setup a new stream instead.

If you use DISCONNECTED, this should cause OBS to try restarting the output. It gives a "disconnected retrying in..." dialog IIRC, and the retry in is user-configurable
___
*[plugins/caffeine/caffeine-output.c, line 745 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8qYMFEm5X1evGAjLg:-LU8qYMFEm5X1evGAjLh:btq24oy) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L745)):*
> ```C
> 		pthread_mutex_lock(&context->stream_mutex);
> 		context->broadcast_info->is_mutating_feed = true;
> 		pthread_mutex_unlock(&context->stream_mutex);
> ```

Since this thread only ever writes and the other thread only ever reads this value, I think some other construct would make more sense, e.g. a semaphore or atomic bool.
___
*[UI/window-basic-main-outputs.cpp, line 51 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8bcY48OYcqZ6HtHh0:-LU8bcY48OYcqZ6HtHh1:bsf9rld) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/UI/window-basic-main-outputs.cpp#L51)):*
> ```cpp
> //            QDesktopServices::openUrl(url);
> //        }
> //    }
> ```

Should this be uncommented? ;)

**Review by trilorez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13)* status: all files reviewed, 7 unresolved discussions (waiting on @cogwheel and @davidc604)

___
*[plugins/caffeine/caffeine-api.c, line 1013 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8iQVj9mQfwtj6iIeJ:-LU9GOLKBdeJb1tc3i-O:b5qtlb8) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-api.c#L1013)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Do we want to do anything with this value besides forwarding it in other requests? e.g. `<insert whatever Lucio does here>`
</blockquote></details>

What does Lucio do again?
___
*[plugins/caffeine/caffeine-output.c, line 350 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8n3Zs31v4cQdvlgL8:-LU95KfBCNeBYlnVCGTW:b-24rn02) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L350)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Would it make sense for the new functions above here (request_stage_update, set_string, generate_unique_id, transfer_stage_data) to live in caffeine-api instead?
</blockquote></details>

I was thinking about that. Also based on the way it's used now, I could just expose `request_stage_update` in caffeine-api and hide all of the stage response stuff internally.
___
*[plugins/caffeine/caffeine-output.c, line 372 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8nWBWDzSVNekldtP2:-LU96GI90SOZHY048-MM:b2nhtan) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L372)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Should be `const` since this isn't being duped?
</blockquote></details>

Yup
___
*[plugins/caffeine/caffeine-output.c, line 526 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8fs1B2WIrr0RBhGB5:-LU96M8NEcedI62IfJEF:b-w5gdsz) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L526)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Looks like there's some mixed spaces & tabs in here
</blockquote></details>

Hopefully fixed
___
*[plugins/caffeine/caffeine-output.c, line 532 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8oZAn3j8QGKwJFcw2:-LU96REB4x3Q2UzBFC0j:bqog80t) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L532)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Nit: maybe `fallback_id` would be a better name here?
</blockquote></details>

Agreed
___
*[plugins/caffeine/caffeine-output.c, line 727 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8b68aDISEWTn0kr_a:-LU96nat64enNP6cU86G:b-vyjkpo) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L727)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

> Note: if stream heartbeating fails, the broadcast goes offline. In the future it would be better to try to setup a new stream instead.

If you use DISCONNECTED, this should cause OBS to try restarting the output. It gives a "disconnected retrying in..." dialog IIRC, and the retry in is user-configurable
</blockquote></details>

Cool, done
___
*[plugins/caffeine/caffeine-output.c, line 745 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8qYMFEm5X1evGAjLg:-LU9FD-A4G2ZeJ0q-As0:b-lovv2s) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L745)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Since this thread only ever writes and the other thread only ever reads this value, I think some other construct would make more sense, e.g. a semaphore or atomic bool.
</blockquote></details>

Went with atomic bool
___
*[UI/window-basic-main-outputs.cpp, line 51 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8bcY48OYcqZ6HtHh0:-LU9FHkmA8G0019KJ_X3:b-hfpf7o) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/UI/window-basic-main-outputs.cpp#L51)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Should this be uncommented? ;)
</blockquote></details>

Right, I need to figure out a decent way to define staging environment in one place

**Review by cogwheel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13)* status: all files reviewed, 4 unresolved discussions (waiting on @cogwheel, @trilorez, and @davidc604)

___
*[plugins/caffeine/caffeine-output.c, line 811 at r4](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU9QaSCBw7MbTXyZgcy:-LU9QaSCBw7MbTXyZgcz:bpcdhxu) ([raw file](https://github.com/caffeinetv/obs-studio/blob/1df591815487e639958d78fa59f0779e012e1a63/plugins/caffeine/caffeine-output.c#L811)):*
> ```C
> 
> 	trace();
> 	os_set_thread_name("Caffeine broadcast longpoll");
> ```

I'd remove "broadcast" from the name to make it easier to differentiate the threads at a glance (or at all, in narrow UI elements, e.g. the Visual Studio thread dropdown menu)

**Review by davidc604 — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13)* status: all files reviewed, 4 unresolved discussions (waiting on @cogwheel and @trilorez)

**Review by cogwheel — COMMENTED** [review]
In libobs/obs-config.h, change the LIBOBS_API_MAJOR/MINOR/PATCH_VER to 22, 2, and 0 to match what the version check will be expecting for newreyes

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-:-LU9ay8K0o-090eyt2vI:b-yyyx3p)* status: all files reviewed, 4 unresolved discussions (waiting on @cogwheel and @trilorez)

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13)* status: all files reviewed, 4 unresolved discussions (waiting on @cogwheel and @trilorez)

___
*[plugins/caffeine/caffeine-api.c, line 1013 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8iQVj9mQfwtj6iIeJ:-LU9mLxE6-Yb_6nTPMYw:brw34vz) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-api.c#L1013)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

What does Lucio do again?
</blockquote></details>

I thought it was reducing the frame size or lowering the desired bit rate from webrtc, but it looks like it's just showing the network error icon. I think OBS has a network indicator we can affect...

**Review by trilorez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @cogwheel, @davidc604, and @trilorez)

___
*[plugins/caffeine/caffeine-output.c, line 811 at r4](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU9QaSCBw7MbTXyZgcy:-LUC3HZk5wwwUgaIJAT1:bb6un1j) ([raw file](https://github.com/caffeinetv/obs-studio/blob/1df591815487e639958d78fa59f0779e012e1a63/plugins/caffeine/caffeine-output.c#L811)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

I'd remove "broadcast" from the name to make it easier to differentiate the threads at a glance (or at all, in narrow UI elements, e.g. the Visual Studio thread dropdown menu)
</blockquote></details>

Done

**Review by trilorez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @cogwheel, @davidc604, and @trilorez)

___
*[plugins/caffeine/caffeine-output.c, line 350 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8n3Zs31v4cQdvlgL8:-LUCXQ4c1FYS28aIjD1Q:bb6un1j) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-output.c#L350)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

I was thinking about that. Also based on the way it's used now, I could just expose `request_stage_update` in caffeine-api and hide all of the stage response stuff internally.
</blockquote></details>

Done

**Review by trilorez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @cogwheel and @davidc604)

___
*[plugins/caffeine/caffeine-api.c, line 1013 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8iQVj9mQfwtj6iIeJ:-LUCbafR59C2XIDgC7kU:bb6un1j) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/plugins/caffeine/caffeine-api.c#L1013)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

I thought it was reducing the frame size or lowering the desired bit rate from webrtc, but it looks like it's just showing the network error icon. I think OBS has a network indicator we can affect...
</blockquote></details>

Done

**Review by cogwheel — COMMENTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13)* status: all files reviewed, 1 unresolved discussion (waiting on @cogwheel)

**Review by trilorez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @cogwheel and @davidc604)

___
*[UI/window-basic-main-outputs.cpp, line 51 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-LU8bcY48OYcqZ6HtHh0:-LUCgI7J4E2BguXAEok7:bb6un1j) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12315af838749a452aaf984e0b7391f0182500a4/UI/window-basic-main-outputs.cpp#L51)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Right, I need to figure out a decent way to define staging environment in one place
</blockquote></details>

Done

**Review by cogwheel — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-:-LUDT02IBlvxRkPnjePg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cogwheel — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r9.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/13#-:-LV5gCwGCqn7odynWCBy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
