### PR TITLE
UI,plugins,libobs: Support caffeine in autoconfig wizard

### PR DESCRIPTION
**Pull request by cogwheel**
This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/48)

### CODE REVIEW

**Review by trilorez — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/48)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @cogwheel and @trilorez)

___
*[UI/window-basic-auto-config-test.cpp, line 1048 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/48#-LhaqcL3BvoIYOqzruLX:-LhaqcL3BvoIYOqzruLY:bia0ib2) ([raw file](https://github.com/caffeinetv/obs-studio/blob/52e7896271dba0135953de8d45cbcab80611bf0a/UI/window-basic-auto-config-test.cpp#L1048)):*
> ```cpp
> 		new QLabel(fpsStr, ui->finishPage));
> 
> 	QTimer::singleShot(0, [this]() {
> ```

Why is this needed? Layout issues?
___
*[UI/window-basic-settings-stream.cpp, line 257 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/48#-LhbEZKm4dnP_1ynw1KL:-LhbEZKm4dnP_1ynw1KM:b-pfmvhm) ([raw file](https://github.com/caffeinetv/obs-studio/blob/52e7896271dba0135953de8d45cbcab80611bf0a/UI/window-basic-settings-stream.cpp#L257)):*
> ```cpp
> static inline bool can_auth_service(const std::string &service)
> {
> 	Auth::Type auth_type = Auth::AuthType(service);
> ```

I realize these are just updating how the current obs codebase does it, but since this is duplicated elsewhere it might be worth extracting to a common function

**Review by trilorez — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/48)* status: all files reviewed, 2 unresolved discussions (waiting on @cogwheel)

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/48)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @trilorez)

___
*[UI/window-basic-auto-config-test.cpp, line 1048 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/48#-LhaqcL3BvoIYOqzruLX:-LhbwXdY9bkJZw1pShZI:bfgdvd5) ([raw file](https://github.com/caffeinetv/obs-studio/blob/52e7896271dba0135953de8d45cbcab80611bf0a/UI/window-basic-auto-config-test.cpp#L1048)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Why is this needed? Layout issues?
</blockquote></details>

Yep. All the values got squished/overlapped and were illegible
___
*[UI/window-basic-settings-stream.cpp, line 257 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/48#-LhbEZKm4dnP_1ynw1KL:-Lhc0uJZ3koZ-aMKm2hq:b-896fix) ([raw file](https://github.com/caffeinetv/obs-studio/blob/52e7896271dba0135953de8d45cbcab80611bf0a/UI/window-basic-settings-stream.cpp#L257)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

I realize these are just updating how the current obs codebase does it, but since this is duplicated elsewhere it might be worth extracting to a common function
</blockquote></details>

Done.

**Review by trilorez — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/48#-:-LhcADCa7VrK6MuqrR4m:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @trilorez)

**Pull request merged**
