### PR TITLE
Adding ./bootstrap.sh to help set up OS X build

### PR DESCRIPTION
**Pull request by adamroach**
This will greatly simplify getting fresh checkouts setup.

---
This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/91)

### CODE REVIEW

**Comment by turbodavidson** [comment]
It looks good to me Adam but could we rename the file bootstrap-osx.sh or something like that? I believe OBS studio builds on Linux as well, so adding the -osx onto the end would help indicate that it helps on MacOS specifically.

**Comment by turbodavidson** [comment]
Or even just -macos.sh since I think Apple officially released MacOS 11

**Comment by turbodavidson** [comment]
:lgtm:

**Review by prateekshadas — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/91#-:-MOldr2v19Dk-fCPtdAO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @turbodavidson)

**Pull request merged**
