### PR TITLE
External alpha 2

### PR DESCRIPTION
**Pull request by cogwheel**
This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/4)

### CODE REVIEW

**Review by trilorez — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/4)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @cogwheel and @trilorez)

___
*[plugins/caffeine/caffeine-output.c, line 363 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/4#-LTYkyBa7fNobl9Psxct:-LTYkyBb241wVdpPjHdd:b3qpi56) ([raw file](https://github.com/caffeinetv/obs-studio/blob/3eabd9a4b4ed2ca4a40f8f2fdd42b0feb8b65ad8/plugins/caffeine/caffeine-output.c#L363)):*
> ```C
> 	char * foreground_process = get_foreground_process_name();
> 	if (games && foreground_process) {
> 		/* TODO: this is inside out; should have process name at toplevel */
> ```

Any reason that isn't done that way now?
___
*[plugins/caffeine/caffeine-output.c, line 411 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/4#-LTYjBrI-pPEFNK1x_Pz:-LTYjBrI-pPEFNK1x_Q-:b-87fmuz) ([raw file](https://github.com/caffeinetv/obs-studio/blob/3eabd9a4b4ed2ca4a40f8f2fdd42b0feb8b65ad8/plugins/caffeine/caffeine-output.c#L411)):*
> ```C
> 		obs_service_query(service, CAFFEINE_QUERY_BROADCAST_RATING);
> 
> 	struct caffeine_games * games = caffeine_get_supported_games();
> ```

It looks like this requests the games list on every heartbeat. Do we need to do it that often?

**Review by trilorez — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/4)* status: all files reviewed, 2 unresolved discussions (waiting on @cogwheel)

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/4)* status: all files reviewed, 2 unresolved discussions (waiting on @trilorez)

___
*[plugins/caffeine/caffeine-output.c, line 363 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/4#-LTYkyBa7fNobl9Psxct:-LTYwHHMAXpT4GqxgUhO:bd3scrr) ([raw file](https://github.com/caffeinetv/obs-studio/blob/3eabd9a4b4ed2ca4a40f8f2fdd42b0feb8b65ad8/plugins/caffeine/caffeine-output.c#L363)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Any reason that isn't done that way now?
</blockquote></details>

TBH I call my "should" into question... The list is small enough right now and it runs on a separate thread periodically enough that it's not going to have a noticeable impact. If COBS gets its own massive list of supported games this will likely be necessary.

Also, the only dictionary type easily available in OBS land is obs_data_t which would be similar to working with JSON directly.
___
*[plugins/caffeine/caffeine-output.c, line 411 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/4#-LTYjBrI-pPEFNK1x_Pz:-LTYxVxg13NNT62nXr7M:b-a3kajd) ([raw file](https://github.com/caffeinetv/obs-studio/blob/3eabd9a4b4ed2ca4a40f8f2fdd42b0feb8b65ad8/plugins/caffeine/caffeine-output.c#L411)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

It looks like this requests the games list on every heartbeat. Do we need to do it that often?
</blockquote></details>

This may be a naming issue... this function creates the broadcast and sets the stage live before entering the heartbeat loop. So this should only run once per "start streaming"

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/4)* status: all files reviewed, 2 unresolved discussions (waiting on @cogwheel and @trilorez)

___
*[plugins/caffeine/caffeine-output.c, line 411 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/4#-LTYjBrI-pPEFNK1x_Pz:-LTYyMO_DO5gAulwiEYJ:b-9es7pc) ([raw file](https://github.com/caffeinetv/obs-studio/blob/3eabd9a4b4ed2ca4a40f8f2fdd42b0feb8b65ad8/plugins/caffeine/caffeine-output.c#L411)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

This may be a naming issue... this function creates the broadcast and sets the stage live before entering the heartbeat loop. So this should only run once per "start streaming"
</blockquote></details>

I'll rename this broadcast_thread i think

**Review by trilorez — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/4)* status: all files reviewed, 1 unresolved discussion (waiting on @cogwheel)

___
*[plugins/caffeine/caffeine-output.c, line 411 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/4#-LTYjBrI-pPEFNK1x_Pz:-LTZF6HLEO10sky7eZOe:b-s2ias8) ([raw file](https://github.com/caffeinetv/obs-studio/blob/3eabd9a4b4ed2ca4a40f8f2fdd42b0feb8b65ad8/plugins/caffeine/caffeine-output.c#L411)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

I'll rename this broadcast_thread i think
</blockquote></details>

Ah I see

**Comment by cogwheel** [comment]
___
*[plugins/caffeine/caffeine-output.c, line 411 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/4#-LTYjBrI-pPEFNK1x_Pz:-LTZkLly9h6V2i5u0W40:bb6un1j) ([raw file](https://github.com/caffeinetv/obs-studio/blob/3eabd9a4b4ed2ca4a40f8f2fdd42b0feb8b65ad8/plugins/caffeine/caffeine-output.c#L411)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Ah I see
</blockquote></details>

Done

**Review by trilorez — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by trilorez — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cogwheel — COMMENTED** [review]
We'll probably do some squashing/rebasing later, but I'd like to stick with OBS commit message format (described here: https://obsproject.com/blog/how-to-contribute-to-open-source )

so this would be `caffeine: Address some warnings`

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/4#-:-LTi1LT3-KB6mQ81goC8:bnr5wx7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
