### PR TITLE
caffeine: Handle stream takeover

### PR DESCRIPTION
**Pull request by cogwheel**
NOTE: This also requires a corresponding libwebrtc change

https://github.com/caffeinetv/webrtc/commit/c732ca5d852671dc89fc5fdca32b4daf0f6dd0a2

---
This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/10)

### CODE REVIEW

**Review by trilorez — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/10)* status: all files reviewed, 2 unresolved discussions (waiting on @cogwheel and @davidc604)

___
*[plugins/caffeine/caffeine-api.c, line 1168 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/10#-LTzErnw6LotzCcuch3o:-LTzErnw6LotzCcuch3p:bfe8ory) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12adc06ade7aa34af1247e0c8fed0de27ee83586/plugins/caffeine/caffeine-api.c#L1168)):*
> ```C
> 
> 	struct caffeine_stage_response result = { NULL, 0 };
> ```

This doesn't technically matter but I think you've got `NULL` and `0` swapped. I would just do `= {};`
___
*[plugins/caffeine/caffeine-api.c, line 1310 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/10#-LTzFBu80w5Rc2FJYRT4:-LTzFBu80w5Rc2FJYRT5:b-ucssow) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12adc06ade7aa34af1247e0c8fed0de27ee83586/plugins/caffeine/caffeine-api.c#L1310)):*
> ```C
> 	struct caffeine_credentials * creds)
> {
> 	struct caffeine_stage_response result = { NULL, 0 };
> ```

`= {}`

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/10)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @trilorez and @davidc604)

___
*[plugins/caffeine/caffeine-api.c, line 1168 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/10#-LTzErnw6LotzCcuch3o:-LTzGznbCWukTB6fBwVt:b-896fix) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12adc06ade7aa34af1247e0c8fed0de27ee83586/plugins/caffeine/caffeine-api.c#L1168)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

This doesn't technically matter but I think you've got `NULL` and `0` swapped. I would just do `= {};`
</blockquote></details>

Done.
___
*[plugins/caffeine/caffeine-api.c, line 1310 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/10#-LTzFBu80w5Rc2FJYRT4:-LTzGyum8JoPFwJ3uBMN:b-896fix) ([raw file](https://github.com/caffeinetv/obs-studio/blob/12adc06ade7aa34af1247e0c8fed0de27ee83586/plugins/caffeine/caffeine-api.c#L1310)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

`= {}`
</blockquote></details>

Done.

**Review by trilorez — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @davidc604)

**Review by trilorez — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @davidc604)

**Review by cogwheel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/10#-:-LTzHNXK5tmtKtMrOTLB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @davidc604)

**Review by cogwheel — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @davidc604)

**Review by cogwheel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/10#-:-LTzH_foAV_IssETXCgp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @davidc604)

**Review by cogwheel — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @davidc604)

**Pull request merged**
