### PR TITLE
cmake: Adjust libcaffeine to new CPack packages

### PR DESCRIPTION
**Pull request by Xaymar**
libcaffeines exported packages now follow a slightly different standard and define the libcaffeine hidden target, which can be linked to to automatically have include directories and libraries defined. Additionally one can use any of the defined variables in libcaffeineConfig.cmake to enhance a packaging script.

---
This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21)

### CODE REVIEW

**Comment by Xaymar** [comment]
Binaries are now correctly copied into the additional_install_files directory for debug and release.

**Review by cogwheel — CHANGES_REQUESTED** [review]
Can you update `plugins/caffeine/README.rst` with any new steps that are necessary?

I'm not entirely sure how this works, but I assume you've tested both scenarios (downloaded CPack vs. having the source tree)

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-LdPvGQDA_kvld-477Vu:bhheg3k)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cogwheel — CHANGES_REQUESTED** [review]
Testing... (having trouble with Reviewable)

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-LdPwRLk-Ik6t-N5fNH5:b-yak22)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Xaymar** [comment]
Right now I only have the code for the CPack install. I'll add some for the non-CPack one, shouldn't take long. (I wasn't planning for people using libcaffeine as an source tree dependency, my bad.)

**Review by cogwheel — CHANGES_REQUESTED** [review]
Ok. Thanks. That will better support the current workflow of parallel changes in OBS & libcaffeine

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-LdQNmq75Rkv4mBeocBj:bpk5pwj)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Xaymar** [comment]
Added support for both CPack archive and project. While it is preferred to use the CPack archive (simply because it can be generated quicker, and doesn't require as much manual code), this should allow quicker iteration in development. Supported build structures are build32, build64, build/32, build/64 and the normal build. 

I've also adjusted the README.rst to state the new way to configure libcaffeine. You now define LIBCAFFEINE_DIR, as expected by find_package/Find Modules, which will be used as a baseline directory for searching all other content.

**Review by cogwheel — CHANGES_REQUESTED** [review]
Did you push those changes? I don't see any new commits on the branch...

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-LddogyS26pjfICVfGF5:bb9p9y2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Xaymar** [comment]
I pushed them to another branch woops. Will push them here.

**Comment by Xaymar** [comment]
Both AppVeyor and Travis are currently failing at the fact that LIBCAFFEINE_DIR is not defined. Did we complete COBS-31 yet or is that still waiting on work?

**Review by cogwheel — CHANGES_REQUESTED** [review]
I closed that as "won't do". I talked to Jim a while back and he agreed to include libcaffeine in the OBS dependencies zip, so it would be redundant.

Of course, now that I say that I realize it means OBS CI should be looking in dependencies2017 for libcaffeine. We can do that separately once it's being included, or feel free to roll that into these changes

> Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-LddvBKBE9bbHjegi3Zl:b-fm7flj)* status: all files reviewed, 2 unresolved discussions (waiting on @Xaymar)

___
*[plugins/caffeine/README.rst, line 7 at r2](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-Lddt9Om6UZ5mfjXrnli:-Lddt9Om6UZ5mfjXrnlj:b8ncdbw) ([raw file](https://github.com/caffeinetv/obs-studio/blob/5c9217aaa3d3a1352b4dfdce0cd8d22941444959/plugins/caffeine/README.rst#L7)):*
> ```reStructuredText
> --------
> 
> 1. Set LIBCAFFEINE_DIR to either your [libcaffeine](https://github.com/caffeinetv/libcaffeine) built project directory, or preferrably set it to the directory of a CPack libcaffeine package.
> ```

I think this would be clearer split into two parts:

1. Download the libcaffeine CPack package, or check out libcaffeine and build it
2. Set LIBCAFFEINE_DIR to the directory where you saved the package or to the checked out repository
___
*[UI/CMakeLists.txt, line 186 at r2](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-LddvpbA6n_ZEv8Nc02j:-LddvpbA6n_ZEv8Nc02k:b-n2xanz) ([raw file](https://github.com/caffeinetv/obs-studio/blob/5c9217aaa3d3a1352b4dfdce0cd8d22941444959/UI/CMakeLists.txt#L186)):*
> ```CMake
> endif()
> 
> if(CAFFEINE_ENABLED OR BROWSER_AVAILABLE_INTERNAL)
> ```

Can you rebase onto latest `caffeinetv/integration` to get these changes?

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21)* status: all files reviewed, 1 unresolved discussion (waiting on @Xaymar)

___
*[UI/CMakeLists.txt, line 186 at r2](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-LddvpbA6n_ZEv8Nc02j:-LddwofICPqbSumHK_3v:btmxjar) ([raw file](https://github.com/caffeinetv/obs-studio/blob/5c9217aaa3d3a1352b4dfdce0cd8d22941444959/UI/CMakeLists.txt#L186)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Can you rebase onto latest `caffeinetv/integration` to get these changes?
</blockquote></details>

Oops looks like you did this while I was commenting.

**Comment by Xaymar** [comment]
> Of course, now that I say that I realize it means OBS CI should be looking in dependencies2017 for libcaffeine. We can do that separately once it's being included, or feel free to roll that into these changes

I see, it should be fairly easy to make it look in DepsPath in addition to every other path.

**Comment by Xaymar** [comment]
I've adjusted it to look for everything in DepsPath too now, which should work with the future plan.

**Review by cogwheel — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-LdiuGRX0FjN71piaR7B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cogwheel — CHANGES_REQUESTED** [review]
The caffeine plugin is being added even if libcaffeine is not found, causing build to fail. I think something needs to be changed in `plugins/CMakeLists.txt`

> Reviewed 2 of 5 files at r1, 1 of 3 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-LdjZP5C8GUg7DKI3d2x:bqlevoa)* status: all files reviewed, 1 unresolved discussion (waiting on @Xaymar)

___
*[cmake/Modules/FindLibcaffeine.cmake, line 28 at r4](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-LdjYYxD6spYKtpSQWeJ:-LdjYYxD6spYKtpSQWeK:bguhh1c) ([raw file](https://github.com/caffeinetv/obs-studio/blob/b9a3222637da39cdeb8c6e8582b445bc5aa3902a/cmake/Modules/FindLibcaffeine.cmake#L28)):*
> ```CMake
>             libcaffeineConfig.cmake
>         HINTS
>             ${search_dir}
> ```

I think it should search the environment for this too, so there doesn't need to be an extra flag on the `cmake` command.

**Review by cogwheel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @cogwheel and @Xaymar)

___
*[cmake/Modules/FindLibcaffeine.cmake, line 13 at r4](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-LdjaQwe09BlxdkX0WhQ:-LdjaQwe09BlxdkX0WhR:bjhe8jx) ([raw file](https://github.com/caffeinetv/obs-studio/blob/b9a3222637da39cdeb8c6e8582b445bc5aa3902a/cmake/Modules/FindLibcaffeine.cmake#L13)):*
> ```CMake
> #
> 
> set(LIBCAFFEINE_DIR "" CACHE PATH "Path to libcaffeine")
> ```

This is using the same variable name for both where to search for libcaffeine and where it's been found. I think this may cause issues getting the search to work.

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @cogwheel and @Xaymar)

___
*[cmake/Modules/FindLibcaffeine.cmake, line 13 at r4](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-LdjaQwe09BlxdkX0WhQ:-LdjafiVEotpgqhV74IA:b-q9d1nn) ([raw file](https://github.com/caffeinetv/obs-studio/blob/b9a3222637da39cdeb8c6e8582b445bc5aa3902a/cmake/Modules/FindLibcaffeine.cmake#L13)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

This is using the same variable name for both where to search for libcaffeine and where it's been found. I think this may cause issues getting the search to work.
</blockquote></details>

Never mind I misread this

**Review by cogwheel — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21)* status: all files reviewed, 1 unresolved discussion (waiting on @Xaymar)

**Comment by Xaymar** [comment]
> The caffeine plugin is being added even if libcaffeine is not found, causing build to fail. I think something needs to be changed in plugins/CMakeLists.txt

That is because the caffeine plugin _requires_ libcaffeine, which will abort the process of building unfortunately. I did not include this in the PR as it was like this before as far as i know.

> I think it should search the environment for this too, so there doesn't need to be an extra flag on the cmake command.

Do you mean also scanning ENV LIBCAFFEINE_DIR? That can be arranged. (I noticed I forgot to replace tabs with spaces there)

**Comment by cogwheel** [comment]
The toplevel cmakelists is doing the `find_package(libcaffeine)` in order to enable/disable various features. You should have access to or LIBCAFFEINE_FOUND in `plugins/CMakeLists.txt` to decide whether to `add_subdirectory(caffeine)`

**Comment by Xaymar** [comment]
Unfortunately as the caffeine plugin can be built without requiring the UI, I've had to add another find_package to the plugins cmakelists and base the result on that. The changes are included in the PR now.

I've also made it look for environement variables called LIBCAFFEINE_DIR, LIBCAFFEINE_DIR32, LIBCAFFEINE_DIR64 now.

**Review by cogwheel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21)* status: all files reviewed, 3 unresolved discussions (waiting on @Xaymar)

___
*[cmake/Modules/FindLibcaffeine.cmake, line 30 at r5](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-Ldk_cmn4d7HarPGMdfC:-Ldk_cmoEB1rhcLPGzto:b-2fv85d) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a5da2d425fb7254164873463209494573ad12cc9/cmake/Modules/FindLibcaffeine.cmake#L30)):*
> ```CMake
>             ENV ${LIBCAFFEINE_DIR}
>             ENV ${DepsPath${BITS}}
>             ENV ${DepsPath}
> ```

These don't seem to be working. I think they're supposed to be:

```
ENV LIBCAFFEINE_DIR${BITS}
ENV LIBCAFFEINE_DIR
ENV DepsPath${BITS}
ENV DepsPath
```
___
*[cmake/Modules/FindLibcaffeine.cmake, line 307 at r5](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-LdkaOjt1qFQRuY4XspV:-LdkaOjt1qFQRuY4XspW:b16pr92) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a5da2d425fb7254164873463209494573ad12cc9/cmake/Modules/FindLibcaffeine.cmake#L307)):*
> ```CMake
> # CPack Archive
> if(LIBCAFFEINE_DIR)
>     find_libcaffeine_cpack()
> ```

I don't think this needs to be inside an `if` anymore
___
*[cmake/Modules/FindLibcaffeine.cmake, line 324 at r5](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-LdkaTk05SuJciTlap5y:-LdkaTk05SuJciTlap5z:b-2guby3) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a5da2d425fb7254164873463209494573ad12cc9/cmake/Modules/FindLibcaffeine.cmake#L324)):*
> ```CMake
> endif()
> if(LIBCAFFEINE_DIR)
>     find_libcaffeine_project()
> ```

same here

**Review by cogwheel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @cogwheel and @Xaymar)

___
*[cmake/Modules/FindLibcaffeine.cmake, line 30 at r5](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-Ldk_cmn4d7HarPGMdfC:-Ldkbbi16zka8ydrLEUP:bvdfa0t) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a5da2d425fb7254164873463209494573ad12cc9/cmake/Modules/FindLibcaffeine.cmake#L30)):*
I'm not sure what's going on but it still isn't finding even after making that change on my end. I have `LIBCAFFEINE_DIR` set to `c:\users\cogwheel\development\projects\libcaffeine\`, I have built all the different configurations so all the libs & bins should be there, but I still get this during configuration:

> -- Could NOT find LIBCAFFEINE (missing: LIBCAFFEINE_INCLUDE_DIR LIBCAFFEINE_LIBRARY_RELWITHDEBINFO LIBCAFFEINE_BINARY_RELWITHDEBINFO LIBCAFFEINE_LIBRARY_DEBUG LIBCAFFEINE_BINARY_DEBUG)

Is the "project" version is working on your end?

**Comment by Xaymar** [comment]
> Is the "project" version is working on your end?

Yes, my build structure is:
- <root>: Source code
- <root>/build: Directory containing build projects
- <root>/build/64: 64-bit build configuration
- <root>/build/64/<RelWithDebInfo|Debug|MinSizeRel|Release>: Individual releases

It tries to find caffeine.h in <root>/include, and the rest of the files in build, build32, build64.

**Review by cogwheel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-LdkcrYVAYuOqQF03K9g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[cmake/Modules/FindLibcaffeine.cmake, line 30 at r5](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-Ldk_cmn4d7HarPGMdfC:-LdkckYH6jmYz4sOuoxF:b-7qtow4) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a5da2d425fb7254164873463209494573ad12cc9/cmake/Modules/FindLibcaffeine.cmake#L30)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

I'm not sure what's going on but it still isn't finding even after making that change on my end. I have `LIBCAFFEINE_DIR` set to `c:\users\cogwheel\development\projects\libcaffeine\`, I have built all the different configurations so all the libs & bins should be there, but I still get this during configuration:

> -- Could NOT find LIBCAFFEINE (missing: LIBCAFFEINE_INCLUDE_DIR LIBCAFFEINE_LIBRARY_RELWITHDEBINFO LIBCAFFEINE_BINARY_RELWITHDEBINFO LIBCAFFEINE_LIBRARY_DEBUG LIBCAFFEINE_BINARY_DEBUG)

Is the "project" version is working on your end?
</blockquote></details>

Oh it looks like it was because of the if statements below

**Review by cogwheel — CHANGES_REQUESTED** [review]
I should've waited for configure to finish... Now I'm seeing 

> CMake Error at cmake/Modules/FindLibcaffeine.cmake:266 (add_library):
  add_library cannot create imported target "libcaffeine" because another
  target with the same name already exists.

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-Ldkd-M61SBhh69PX1UH:b-l2chfx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Xaymar** [comment]
Applied the requested changes.

**Review by cogwheel — COMMENTED** [review]
The configuration succeeds now, but build fails with

> cannot open input file 'libcaffeine-NOTFOUND.obj'

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-Ldkf7AW-6bQgIkQGuW1:bxauonl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @cogwheel)

**Review by cogwheel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @cogwheel and @Xaymar)

___
*[plugins/caffeine/CMakeLists.txt, line 31 at r7](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-LdkosGB-FCe0cQQbLEy:-LdkosGB-FCe0cQQbLEz:bm5mrau) ([raw file](https://github.com/caffeinetv/obs-studio/blob/c1166aca08bf8da777e72453e78b6fa9e410cf9e/plugins/caffeine/CMakeLists.txt#L31)):*
> ```CMake
> 	${THREADS_LIBRARIES}
> 	libobs
> 	libcaffeine)
> ```

If I remove libcaffeine from here the build succeeds but only in Release, I'm assuming because `${LIBCAFFEINE_LIBRARY}` is pointing to the RelWithDebInfo build

**Review by cogwheel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @cogwheel and @Xaymar)

___
*[plugins/caffeine/CMakeLists.txt, line 31 at r7](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-LdkosGB-FCe0cQQbLEy:-Ldkp3wq--eSYWzo1ITi:bfpy5hg) ([raw file](https://github.com/caffeinetv/obs-studio/blob/c1166aca08bf8da777e72453e78b6fa9e410cf9e/plugins/caffeine/CMakeLists.txt#L31)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

If I remove libcaffeine from here the build succeeds but only in Release, I'm assuming because `${LIBCAFFEINE_LIBRARY}` is pointing to the RelWithDebInfo build
</blockquote></details>

Here and UI as well

**Review by cogwheel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @cogwheel and @Xaymar)

___
*[cmake/Modules/FindLibcaffeine.cmake, line 303 at r7](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-LdkpHIG5fKoVLuNAM-R:-LdkpHIG5fKoVLuNAM-S:b-v4hrum) ([raw file](https://github.com/caffeinetv/obs-studio/blob/c1166aca08bf8da777e72453e78b6fa9e410cf9e/cmake/Modules/FindLibcaffeine.cmake#L303)):*
> ```CMake
> 		message("Target libcaffeine already defined, skipping.")
> 	endif()
>     
> ```

I think this file needs to be reformatted

**Review by cogwheel — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21)* status: all files reviewed, 2 unresolved discussions (waiting on @Xaymar)

**Comment by Xaymar** [comment]
Did you build libcaffeine for _all_ configurations or just Release? The current code looks for all configurations, in order for all configurations to work.

**Comment by Xaymar** [comment]
> The configuration succeeds now, but build fails with
>
>     cannot open input file 'libcaffeine-NOTFOUND.obj'

Ah, this should be fixed now. I have also adjusted it to only require a built Release-like configuration at minimum. The project version will now look for things in this order:

* RelWithDebInfo will first search for itself, then Release, then MinSizeRel.
* Release will search for itself, then RelWithDebInfo, then MinSizeRel.
* MinSizeRel will search for itself, then RelWithDebInfo, then MinSizeRel.
* Debug will search for itself, then RelWithDebInfo, then Release, then MinSizeRel.

While ideally you should be building all configurations (use batch building or a script invoking cmake), this will enable partial configurations to work. Note that non-Debug builds can't link to a Debug binary, so you will need to have built at least one Release configuration.

> tabs, spaces

I have adjusted it as requested.

**Review by cogwheel — COMMENTED** [review]
Yes, I had built all the configurations. I'll give this a shot

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-Ldo-WWy4oe2dDiE3Qt8:bc6u5n1)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @cogwheel and @Xaymar)

**Review by cogwheel — COMMENTED** [review]
Now all the configurations are building, but they're all linking to `libcaffeined` instead of the configuration-specific lib, so they fail to run. The bins are being copied to the correct `additional_install_files` locations, it's just the linking that seems to be wrong.

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-Ldo3ybNDrk2gATqehWV:b-uqwt0n)* status: all files reviewed, 1 unresolved discussion (waiting on @Xaymar)

**Review by cogwheel — COMMENTED** [review]
I'm also noticing that additional_install_files only seems to differentiate release & debug, not all 4 configurations. So I guess OBS should only be looking for Debug and RelWithDebInfo

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-Ldo56AeCthxRmv1vnn4:b6v92az)* status: all files reviewed, 1 unresolved discussion (waiting on @Xaymar)

**Comment by Xaymar** [comment]
I believe I have fixed all issues now, including the linking and copying issue. I've successfully built it in all configurations and ran it in all configurations.

**Review by cogwheel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/21#-:-LdzmxAd2oSQAVdFvBTK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
