### PR TITLE
COBS-103

### PR DESCRIPTION
**Pull request by turbodavidson**
Fixed queue traversal

### CODE REVIEW

**Comment by Xaymar** [comment]
What exactly were the differences observed? I couldn't find any in my testing.

**Comment by Xaymar** [comment]
Nevermind the previous message, after rebuilding I can indeed confirm that this fixes the queueing problem.

**Review by Xaymar — APPROVED** [review]

**Comment by Xaymar** [comment]
It might be possible to optimize this with a circlebuf instead. I haven't delved too deep into it yet, but if we can avoid alloc/dealloc then we probably can make even weaker machines support this as well.

**Comment by Xaymar** [comment]
Mac error fixed by #83

**Review by prateekshadas — APPROVED** [review]
LGTM

**Pull request merged**
