### PR TITLE
COBS-37: Show signed-in username for Caffeine in settings

### PR DESCRIPTION
**Pull request by cogwheel**
This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/56)

### CODE REVIEW

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/56)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @trilorez)

___
*[UI/window-basic-settings-stream.cpp, line 8 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/56#-LhptZXSDRwfT-CUydpE:-LhptZXSDRwfT-CUydpF:bxz0ij5) ([raw file](https://github.com/caffeinetv/obs-studio/blob/4ba84e27e97618ccaf2f5ec60170328e2d45472d/UI/window-basic-settings-stream.cpp#L8)):*
> ```cpp
> #include "window-basic-main.hpp"
> #include "qt-wrappers.hpp"
> #include "auth-caffeine.hpp"
> ```

This and most of the other changes here should be conditionally compiled when CAFFEINE_ENABLED

**Review by trilorez — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/56)* status: all files reviewed, 2 unresolved discussions (waiting on @cogwheel)

*[a discussion](https://reviewable.io/reviews/caffeinetv/obs-studio/56#-Lhq954PAypoRwTV9RKR:-Lhq954PAypoRwTV9RKS:b-ywp6pt) (no related file):*
When I switch services, is it supposed to still show that I'm signed in as my caffeine username?










---
___
*[UI/window-basic-settings-stream.cpp, line 8 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/56#-LhptZXSDRwfT-CUydpE:-Lhq8y_gAEiDpNlLVa43:biudgsc) ([raw file](https://github.com/caffeinetv/obs-studio/blob/4ba84e27e97618ccaf2f5ec60170328e2d45472d/UI/window-basic-settings-stream.cpp#L8)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

This and most of the other changes here should be conditionally compiled when CAFFEINE_ENABLED
</blockquote></details>

It doesn't look like this is currently the case?

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/56)* status: all files reviewed, 2 unresolved discussions (waiting on @cogwheel and @trilorez)

___
*[UI/window-basic-settings-stream.cpp, line 8 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/56#-LhptZXSDRwfT-CUydpE:-LhqBmVb8YxtUpoRciIr:b-b4mncr) ([raw file](https://github.com/caffeinetv/obs-studio/blob/4ba84e27e97618ccaf2f5ec60170328e2d45472d/UI/window-basic-settings-stream.cpp#L8)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

It doesn't look like this is currently the case?
</blockquote></details>

Right. I blocked this myself because it broke CI on linux

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/56)* status: all files reviewed, 2 unresolved discussions (waiting on @cogwheel and @trilorez)

*[a discussion](https://reviewable.io/reviews/caffeinetv/obs-studio/56#-Lhq954PAypoRwTV9RKR:-LhqByPU-PrUKH7dL6Kl:bb710yj) (no related file):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

When I switch services, is it supposed to still show that I'm signed in as my caffeine username?










</blockquote></details>

Nope

---

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/56)* status: all files reviewed, 3 unresolved discussions (waiting on @cogwheel and @trilorez)

___
*[UI/window-basic-settings-stream.cpp, line 308 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/56#-LhqC60o6q2CsT7VL-G6:-LhqC60o6q2CsT7VL-G7:b-s0nip4) ([raw file](https://github.com/caffeinetv/obs-studio/blob/4ba84e27e97618ccaf2f5ec60170328e2d45472d/UI/window-basic-settings-stream.cpp#L308)):*
> ```cpp
> 		ui->streamKeyLabel->setVisible(!hidden_key);
> 		ui->authSignedInAs->setVisible(authenticated);
> 		ui->authSignedInAsLabel->setVisible(authenticated);
> ```

^^ This is why the username is still showing up after switching services i think... will fix

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/56)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @trilorez)

*[a discussion](https://reviewable.io/reviews/caffeinetv/obs-studio/56#-Lhq954PAypoRwTV9RKR:-LhqsFt21F77pRogAybx:b-896fix) (no related file):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Nope
</blockquote></details>

Done.

---

**Review by trilorez — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/56#-:-Lhr7cJL4BS7vcTRMwNT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
