### PR TITLE
COBS-12: Add Stream Utility Window

### PR DESCRIPTION
**Pull request by Xaymar**
Adds the requested stream utility window to update rating and title, and eventually display viewers and credits, and links to where the web panel might be.

- [x] Panel is dockable and shows up in the menu.
- [ ] Panel retains dock state and position across OBS starts.
- [x] Set Rating for Broadcast.
- [x] Get Rating for Broadcast.
- [x] Set Title for Broadcast.
- [x] Get Title for Broadcast.
- [x] View on Web button opens Browser to correct URL.

---
This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/26)

### CODE REVIEW

**Comment by Xaymar** [comment]
Storing notes for implementation:

- Viewer/Credits count not used, can be removed.
- View on web button: caffeint.tv/username
- Title and rating stored by OBS not libcaffeine.

**Comment by Xaymar** [comment]
The title and rating are stored in the obs main config, but i seem to have no way to go from there into the output or service. In fact, both the output and service don't seem to exist until way after the start of obs.

Additionally updating the rating and title with libcaffeine does not work at the current time. I am not sure why, but the caffeine.tv stream will always have the same title even if updated during the stream.

**Comment by Xaymar** [comment]
According to Jim, retaining dock state and position is managed by the auth provider, which is unusual, but not impossible. For now this is not included.

Title and Rating updates now work and are sent correctly to the service, which then begins streaming correctly as expected.

**Review by cogwheel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/26)* status: all files reviewed, 6 unresolved discussions (waiting on @Xaymar)

___
*[UI/CMakeLists.txt, line 299 at r2](https://reviewable.io/reviews/caffeinetv/obs-studio/26#-Lfzb1q-1hnlwuaR7gmT:-Lfzb1q-1hnlwuaR7gmU:b-hpz2dp) ([raw file](https://github.com/caffeinetv/obs-studio/blob/22646e80aef9f10a003881c2ff0ab9ef64777f93/UI/CMakeLists.txt#L299)):*
> ```CMake
> 	audio-encoders.cpp
> 	qt-wrappers.cpp
> 	window-caffeine.cpp)
> ```

There should be an `if(CAFFEINE_ENABLED)` that appends the caffeine files to these lists. Otherwise it breaks CI when caffeine isn't present.
___
*[UI/CMakeLists.txt, line 359 at r2](https://reviewable.io/reviews/caffeinetv/obs-studio/26#-LfzbsK09wmXawj5Me0c:-LfzbsK09wmXawj5Me0d:b-34vmyd) ([raw file](https://github.com/caffeinetv/obs-studio/blob/22646e80aef9f10a003881c2ff0ab9ef64777f93/UI/CMakeLists.txt#L359)):*
> ```CMake
> 	qt-wrappers.hpp
> 	clickable-label.hpp
> 	window-caffeine.hpp)
> ```

See above
___
*[UI/CMakeLists.txt, line 378 at r2](https://reviewable.io/reviews/caffeinetv/obs-studio/26#-LfzbtnP-9aRvh4l-gmr:-LfzbtnP-9aRvh4l-gms:b-34vmyd) ([raw file](https://github.com/caffeinetv/obs-studio/blob/22646e80aef9f10a003881c2ff0ab9ef64777f93/UI/CMakeLists.txt#L378)):*
> ```CMake
> 	forms/OBSRemux.ui
> 	forms/OBSAbout.ui
> 	forms/CaffeinePanel.ui)
> ```

See above
___
*[UI/CMakeLists.txt, line 382 at r2](https://reviewable.io/reviews/caffeinetv/obs-studio/26#-Lfzb2nj3KZ2ykNql2dt:-Lfzb2nj3KZ2ykNql2du:b-5cchsp) ([raw file](https://github.com/caffeinetv/obs-studio/blob/22646e80aef9f10a003881c2ff0ab9ef64777f93/UI/CMakeLists.txt#L382)):*
> ```CMake
> set(obs_QRC
> 	forms/obs.qrc
> 	forms/caffeine.qrc)
> ```

I don't think this is supposed to be here. Only the obs.qrc exists and cmake fails for me unless I remove this.
___
*[UI/window-caffeine.cpp, line 68 at r2](https://reviewable.io/reviews/caffeinetv/obs-studio/26#-LfzYr68EZ5N41tw_Bvp:-LfzYr68EZ5N41tw_Bvq:b-4uph6q) ([raw file](https://github.com/caffeinetv/obs-studio/blob/22646e80aef9f10a003881c2ff0ab9ef64777f93/UI/window-caffeine.cpp#L68)):*
> ```cpp
> 	const char* title = config_get_string(main->Config(), "Caffeine", "Title");
> 	if (!title) {
> 		return std::string("Live on Caffeine!");
> ```

The default title should be in the localization file and LIVE should be all-acps.
___
*[UI/data/locale/en-US.ini, line 943 at r2](https://reviewable.io/reviews/caffeinetv/obs-studio/26#-Lfz_9eI33nHbMjK5JFB:-Lfz_9eJ10USIjmbGSOi:b-gjzssg) ([raw file](https://github.com/caffeinetv/obs-studio/blob/22646e80aef9f10a003881c2ff0ab9ef64777f93/UI/data/locale/en-US.ini#L943)):*
> ```INI
> Caffeine.Dock.UpdateRatingAndTitle="Update rating and title"
> Caffeine.Dock.ViewOnWeb="View on Web"
> Caffeine.Dock.ViewOnWebDescription="<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0//EN' 'http://www.w3.org/TR/REC-html40/strict.dtd'>\n<html><head><meta name='qrichtext' content='1' /><style type='text/css'>\np, li { white-space: pre-wrap; }\n</style></head><body>\n<p>View on web to see credits, viewers,<br />\nand chat with your audience.</p></body></html>"
> ```

I don't think HTML should be in the localization file. This should just be the translatable string `"View on web to see credits, viewers,\nand chat with your audience"`.

**Comment by Xaymar** [comment]
> I don't think HTML should be in the localization file. This should just be the translatable string "View on web to see credits, viewers,\nand chat with your audience".

\n is just shown as \n for some reason. And adding a new line converts the whole thing into Qt HTML. So no idea how I should fix that.

**Comment by Xaymar** [comment]
> There should be an if(CAFFEINE_ENABLED) that appends the caffeine files to these lists. Otherwise it breaks CI when caffeine isn't present.
> I don't think this is supposed to be here. Only the obs.qrc exists and cmake fails for me unless I remove this.

Fixed.

> The default title should be in the localization file and LIVE should be all-acps.

Fixed.

> I don't think HTML should be in the localization file. This should just be the translatable string "View on web to see credits, viewers,\nand chat with your audience".

Tried and it literally shows "View on web to see credits, viewers,\nand chat with your audience". Not sure if QLabel understands \n.

**Comment by Xaymar** [comment]
> Tried and it literally shows "View on web to see credits, viewers,\nand chat with your audience". Not sure if QLabel understands \n.

Somehow works now? It now correctly shows as two lines, whereas it before only had one and showed the \n as normal text. Guess there was a hidden/invisible unicode character in there.

**Review by cogwheel — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/26)* status: all files reviewed, 1 unresolved discussion (waiting on @Xaymar)

___
*[UI/window-caffeine.cpp, line 22 at r3](https://reviewable.io/reviews/caffeinetv/obs-studio/26#-Lg06j3oBFYbWQvUhkIy:-Lg06j3oBFYbWQvUhkIz:bg534ft) ([raw file](https://github.com/caffeinetv/obs-studio/blob/90f108f462bec9e72a83a3147717fad2a8515b13/UI/window-caffeine.cpp#L22)):*
> ```cpp
> 
> 	caff_setTitle(caffeineInstance, title.c_str());
> 	caff_setRating(caffeineInstance, rating);
> ```

The instance owned by the auth service is not the one managing the broadcast. This means the calls to `caff_setTitle` and `caff_setRating` need to happen in `caffeine-output.c`. The simplest way to do this is probably to rename `game_detection_thread` to something more general (periodic_update_thread?) and put the settings check in there.

**Comment by RoastyToast** [comment]
> Adds the requested stream utility window to update rating and title, and eventually display viewers and credits, and links to where the web panel might be.
> 
> * [x]  Panel is dockable and shows up in the menu.
> * [ ]  Panel retains dock state and position across OBS starts.
> * [x]  Set Rating for Broadcast.
> * [x]  Get Rating for Broadcast.
> * [x]  Set Title for Broadcast.
> * [x]  Get Title for Broadcast.
> * [x]  View on Web button opens Browser to correct URL.
> 
> This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/26)

Really cool changes for the OBS chat. I am a software developer and was thinking to support the development as well as possible.

One of things I hear hundreds of streamers about is the option to have a chat overlay for streamers with a single monitor that can overlay the game just like the Caffeine app does.

If we look to an example company who did this succesfully as well with other streams is restream.io/chat

I think its good that this becomes available to the OBS client as well let's take a simple example and go for a chat window that can be moved to a spot within the studio by the user and can be undocked which gives it the skills to change its transparency, fonts for chats and notifications and size of the letters within a chat.

If this could be implemented either by your team or with support of me than there can be an option to streamers to have the chat opened overlaying there game without the need to have a second monitor that needs to open the stream to watch the chat.

Overal is this really bad as Caffeine is all about zero latency and quick interactions what is barely to not possible due to the current features.

So these are things I would suggest.

**Comment by Xaymar** [comment]
> The instance owned by the auth service is not the one managing the broadcast. This means the calls to caff_setTitle and caff_setRating need to happen in caffeine-output.c. The simplest way to do this is probably to rename game_detection_thread to something more general (periodic_update_thread?) and put the settings check in there.

That would explain why it didn't update the title and rating. Adjusted it now and it seems to work fine.

**Review by cogwheel — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/26#-:-Lg3ctbt2ofPjemvGbAM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
