### PR TITLE
Show output error

### PR DESCRIPTION
**Pull request by cogwheel**
Error messages during stream start now appear in the error dialog box.

---
This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/5)

### CODE REVIEW

**Review by trilorez — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/5)* status: all files reviewed, 3 unresolved discussions (waiting on @cogwheel and @davidc604)

___
*[plugins/caffeine/caffeine-output.c, line 553 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/5#-LT_DyCl9B0uIUkVSMZB:-LT_DyCl9B0uIUkVSMZC:b-6xl2of) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a84c138410f0fb5af0749d515cec4416f93934d2/plugins/caffeine/caffeine-output.c#L553)):*
> ```C
> 
> 	if (image_data == NULL) {
> 		log_warn("No image data for screenshot");
> ```

Why are these switched from error logs to warning logs?
___
*[plugins/caffeine/caffeine-service.c, line 305 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/5#-LT_EI9h07y4us4zxDmB:-LT_EI9h07y4us4zxDmC:blyx87p) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a84c138410f0fb5af0749d515cec4416f93934d2/plugins/caffeine/caffeine-service.c#L305)):*
> ```C
> }
> 
> #define set_error(fmt, ...) \
> ```

Can this be deduplicated?
___
*[UI/window-basic-main-outputs.hpp, line 19 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/5#-LT_EZHJCH7wjvaDCM37:-LT_EZHJCH7wjvaDCM38:b4jae8l) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a84c138410f0fb5af0749d515cec4416f93934d2/UI/window-basic-main-outputs.hpp#L19)):*
> ```cpp
> 	std::string            outputType;
> 
> 	bool                   hasLastError;
> ```

Would using `!lastError.empty()` as an implicit `hasLastError` be simpler?

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/5)* status: all files reviewed, 3 unresolved discussions (waiting on @trilorez, @cogwheel, and @davidc604)

___
*[plugins/caffeine/caffeine-output.c, line 553 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/5#-LT_DyCl9B0uIUkVSMZB:-LT_oIqSE2kn91QQuSIc:b-jkl685) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a84c138410f0fb5af0749d515cec4416f93934d2/plugins/caffeine/caffeine-output.c#L553)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Why are these switched from error logs to warning logs?
</blockquote></details>

I've noticed that OBS tends to use warn for non-fatal and error for fatal errors. Screenshot errors won't block the stream, so this was for consistency.
___
*[plugins/caffeine/caffeine-service.c, line 305 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/5#-LT_EI9h07y4us4zxDmB:-LT_pVE5-FC8e6CPxiHh:b3prhap) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a84c138410f0fb5af0749d515cec4416f93934d2/plugins/caffeine/caffeine-service.c#L305)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Can this be deduplicated?
</blockquote></details>

yeah, the output could be a param instead. also i forgot to wrap fmt in parens

TODO
___
*[UI/window-basic-main-outputs.hpp, line 19 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/5#-LT_EZHJCH7wjvaDCM37:-LT_q-438SetqCnNfl6g:b-8d4vq) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a84c138410f0fb5af0749d515cec4416f93934d2/UI/window-basic-main-outputs.hpp#L19)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Would using `!lastError.empty()` as an implicit `hasLastError` be simpler?
</blockquote></details>

Seems reasonable

**Review by davidc604 — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/5)* status: all files reviewed, 3 unresolved discussions (waiting on @trilorez and @cogwheel)

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/5)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @davidc604 and @trilorez)

___
*[plugins/caffeine/caffeine-service.c, line 305 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/5#-LT_EI9h07y4us4zxDmB:-LTy1vxN0pP9Kl2AyHyM:bb6un1j) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a84c138410f0fb5af0749d515cec4416f93934d2/plugins/caffeine/caffeine-service.c#L305)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

yeah, the output could be a param instead. also i forgot to wrap fmt in parens

TODO
</blockquote></details>

Done
___
*[UI/window-basic-main-outputs.hpp, line 19 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/5#-LT_EZHJCH7wjvaDCM37:-LTy1yoY5oQfz7n2Atdo:bb6un1j) ([raw file](https://github.com/caffeinetv/obs-studio/blob/a84c138410f0fb5af0749d515cec4416f93934d2/UI/window-basic-main-outputs.hpp#L19)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Seems reasonable
</blockquote></details>

Done

**Review by trilorez — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
