### PR TITLE
caffeine: Handle out of capacity response when adding a feed.

### PR DESCRIPTION
**Pull request by trilorez**
This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/16)

### CODE REVIEW

**Review by cogwheel — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/16)* status: all files reviewed, 3 unresolved discussions (waiting on @trilorez)

___
*[plugins/caffeine/caffeine-output.c, line 340 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/16#-LVuID2w-ki4lW9VFbIH:-LVuID2w-ki4lW9VFbII:b-s73nxc) ([raw file](https://github.com/caffeinetv/obs-studio/blob/b46c60d89b2fdea1903254077a966fb1493d6367/plugins/caffeine/caffeine-output.c#L340)):*
> ```C
> 	request->client_id = client_id;
> 
> 	if (!caffeine_request_stage_update(request, creds, NULL, NULL)) {
> ```

Checking that I understand this correctly: because the request doesn't contain any feeds, it can't return out-of-capacity because it's not trying to reserve any slots?
___
*[plugins/caffeine/caffeine-output.c, line 366 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/16#-LVuHnRtB8CQN2L6d4xd:-LVuHnRuB8n83V61vtbQ:b-bedp1o) ([raw file](https://github.com/caffeinetv/obs-studio/blob/b46c60d89b2fdea1903254077a966fb1493d6367/plugins/caffeine/caffeine-output.c#L366)):*
> ```C
> 	caffeine_set_stage_feed(request->stage, &feed);
> 
>     	bool is_out_of_capacity = false;
> ```

Nit: bad indentation
___
*[plugins/caffeine/caffeine-output.c, line 459 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/16#-LVuIXq67r3TYDHkLh-j:-LVuIXq67r3TYDHkLh-k:bl42161) ([raw file](https://github.com/caffeinetv/obs-studio/blob/b46c60d89b2fdea1903254077a966fb1493d6367/plugins/caffeine/caffeine-output.c#L459)):*
> ```C
> 			  obs_module_text("ErrorStartStream"),
> 			  error,
> 			  caff_error_string(error));
> ```

Nit: it might just be reviewable formatting but the whitespace above looks odd...

**Review by cogwheel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/16#-:-LVuL_Fz7wHZdYxocLnc:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @trilorez)

**Review by trilorez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/16)* status: all files reviewed, 3 unresolved discussions (waiting on @trilorez and @cogwheel)

___
*[plugins/caffeine/caffeine-output.c, line 340 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/16#-LVuID2w-ki4lW9VFbIH:-LVuLvKP9cSczmzQnUAY:b2nhtan) ([raw file](https://github.com/caffeinetv/obs-studio/blob/b46c60d89b2fdea1903254077a966fb1493d6367/plugins/caffeine/caffeine-output.c#L340)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Checking that I understand this correctly: because the request doesn't contain any feeds, it can't return out-of-capacity because it's not trying to reserve any slots?
</blockquote></details>

Yup

**Review by cogwheel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/16#-:-LVuMyMp1KCSR_vab_Ej:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
